# Etapa 1: build da aplicação com Maven
FROM maven:3.9.5-eclipse-temurin-21 as builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: imagem final com o JAR
FROM eclipse-temurin:21-jre
WORKDIR /app

# Copia o JAR do build
COPY --from=builder /app/target/*.jar app.jar

# Define variável de ambiente para produção
ENV SPRING_PROFILES_ACTIVE=prod

# Expõe portas conforme o app Spring usa
EXPOSE 8080

# Roda o aplicativo
ENTRYPOINT ["java", "-jar", "app.jar"]