name: Deploy Docker Validated

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-validated:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node Modules
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Validated Deploy
        run: npm run deployv
